package LLTest;

import de.learnlib.api.SUL;
import drivers.mealy.MealyDriver;

/**
 * Driver to interface the mealy machines generated by SIMPA with learnlib. It implements the interface SUL from learnlib.
 * @author Laurent
 *
 */

public class Driver implements SUL<String, String> {
	
	private MealyDriver driver;
	public String input;
	public String output;
	
	public Driver(MealyDriver md){
		driver=md;
		input="";
		output="";
	}

/*
	public void reset() {
		driver.reset();	
		input ="";
		output="";
	}*/

	@Override
	public String step(String in) {
		String res = driver.execute(in);
		//input +=in;
		//output += res;
		return res;
	}


	@Override
	public void post() {
		driver.reset();
		
	}


	@Override
	public void pre() {
		driver.reset();
		
	}
	

}
